baseURL = "https://staticbackend.dev"
languageCode = "en-ca"
title = "StaticBackend - backend as a service"
enableRobotsTXT = true


[params]
cliversion = "v1.5.0"


[markup.goldmark.renderer]
unsafe=true
